name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/lw-/}

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v1

    - name: Build the Docker image for latest
      run: docker build . --file docker/Dockerfile --tag ${GITHUB_REPOSITORY}:latest

    - name: Build the Docker image for tag
      run: docker build . --file docker/Dockerfile --tag ${GITHUB_REPOSITORY}:${{ steps.get_version.outputs.VERSION }}
      if: startsWith(github.ref, 'refs/tags/')

    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:latest
      if: startsWith(github.ref, 'refs/tags/')

    - name: Push to docker hub VERSION
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:${{ steps.get_version.outputs.VERSION }}
      if: startsWith(github.ref, 'refs/tags/')
